on: [push, pull_request]
name: Test
jobs:
  test-cache:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            gobuild_path: ~/.cache/go-build
          - os: macos-latest
            gobuild_path: ~/Library/Caches/go-build
          - os: windows-latest
            gobuild_path: '%LocalAppData%\go-build'
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - name: Checkout code
      uses: actions/checkout@v2
    - id: gobuildcache
      shell: bash
      run: echo "::set-output name=path::$(go env GOCACHE)"
    - uses: actions/cache@v2
      env:
        # Module download cache
        module_download_cache: ~/go/pkg/mod

        # Build cache
        build_cache: ${{ steps.gobuildcache.outputs.path }}
      with:
        path: |
          ${{ env.module_download_cache }}
          ${{ env.build_cache }}
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Test
      run: go test ./...
